version: "3.8"
services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    restart: always
    networks:
      - restaurant-backend
  eurekaserver:
    image: deysumon99/eurekaserver:1
    build:
      context: EurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - restaurant-backend
  cloudconfigserver:
    image: deysumon99/cloudconfigserver:1
    build:
      context: ConfigServer
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
    depends_on:
      - eurekaserver
    networks:
      - restaurant-backend
  productservice:
    image: deysumon99/productservice:1
    build:
      context: ProductService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
      USER_AUTH_URL: http://userservice:8083
      SPRING_CONFIG_IMPORT: configserver:http://cloudconfigserver:8087
    depends_on:
      - eurekaserver
      - cloudconfigserver
      - zipkin
    networks:
      - restaurant-backend
  userservice:
    image: deysumon99/userservice:1
    build:
      context: UserService
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
      REVIEW_SERVICE_URL: http://productservice:8082
      SPRING_CONFIG_IMPORT: configserver:http://cloudconfigserver:8087
    depends_on:
      - eurekaserver
      - cloudconfigserver
      - productservice
      - zipkin
    networks:
      - restaurant-backend
  feedbackservice:
    image: deysumon99/feedbackservice:1
    build:
      context: FeedbackService
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
      SPRING_CONFIG_IMPORT: configserver:http://cloudconfigserver:8087
    depends_on:
      - eurekaserver
      - cloudconfigserver
      - zipkin
    networks:
      - restaurant-backend
  messagingservice:
    image: deysumon99/messagingservice:1
    build:
      context: MessagingService
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
      SPRING_CONFIG_IMPORT: configserver:http://cloudconfigserver:8087
      USER_AUTH_URL: http://userservice:8083
    depends_on:
      - eurekaserver
      - cloudconfigserver
      - userservice
      - zipkin
    networks:
      - restaurant-backend
  apigateway:
    image: deysumon99/apigateway:1
    build:
      context: ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka
      SPRING_CONFIG_IMPORT: configserver:http://cloudconfigserver:8087
    depends_on:
      - eurekaserver
      - cloudconfigserver
    networks:
      - restaurant-backend

# Networks to be created to facilitate communication between containers
networks:
  restaurant-backend:
